import test from 'node:test';
import assert from 'node:assert/strict';
import { signatureGate, validateContract, type ContractData } from '../lib/contract.ts';
import { structureContract } from '../lib/structure.ts';
import { bindFolder, createRun } from '../lib/run-registry.ts';
import { GET as statusGet } from '../app/api/foxit/status/route.ts';
import { buildContractDocumentText } from '../lib/document.ts';
const sentence='온라인 판매자와 외주 디자이너 간 상품 이미지 제작 계약을 작성해 주세요. 계약 본문의 총액은 1,200,000원이고 지급 일정표에는 1,020,000원으로 기재되어 있습니다. 결과물은 상품 이미지 10개, 수정은 최대 2회, 납기일은 2026년 9월 30일입니다. 결과물의 저작권은 계약금 전액을 지급한 후 판매자에게 이전됩니다.';
const valid:ContractData={partyA:'A',partyB:'B',amount:1200,paymentScheduleAmount:1200,effectiveDate:'2026-09-01',dueDate:'2026-09-30',obligations:['상품 이미지 10개 제작','수정 요청 최대 2회 반영'],copyrightTransferCondition:'계약금 전액 지급 후',requiredClauses:['scope','payment','delivery','copyright'],extraClauses:[{text:'결과물의 저작권은 계약금 전액을 지급한 후 판매자에게 이전됩니다',approved:true}]};
test('all seven deterministic checks pass',()=>assert.equal(validateContract(valid).filter(c=>c.passed).length,7));
test('amount mismatch blocks validation',()=>assert.equal(validateContract({...valid,paymentScheduleAmount:1020}).find(c=>c.id==='amount')?.passed,false));
test('no approval blocks gate',()=>assert.equal(signatureGate({checks:validateContract(valid),humanApprovalRecorded:false,approvedPdfHash:'a',currentPdfHash:'a'}),false));
test('changed PDF hash revokes gate',()=>assert.equal(signatureGate({checks:validateContract(valid,true),humanApprovalRecorded:true,approvedPdfHash:'a',currentPdfHash:'b'}),false));
test('gate opens only on all conditions',()=>assert.equal(signatureGate({checks:validateContract(valid),humanApprovalRecorded:true,approvedPdfHash:'a',currentPdfHash:'a'}),true));
test('normal sentence produces English structured output and preserves copyright transfer condition',()=>{const value=structureContract(sentence);assert.equal(value.partyA,'Online seller');assert.equal(value.partyB,'Freelance designer');assert.equal(value.amount,1200000);assert.equal(value.paymentScheduleAmount,1020000);assert.equal(value.dueDate,'2026-09-30');assert.equal(value.copyrightTransferCondition,'Only after full payment');assert.match(value.extraClauses[0].text,/only after full payment/i)});
test('structure failure has no fallback',()=>assert.throws(()=>structureContract('계약서를 만들어줘'),/STRUCTURE_REQUIRED_FIELD_MISSING/));
test('missing full-payment condition fails required clause',()=>assert.equal(validateContract({...valid,copyrightTransferCondition:''}).find(c=>c.id==='required-clauses')?.passed,false));
test('immediate-on-signing copyright transfer fails required clause',()=>assert.equal(validateContract({...valid,copyrightTransferCondition:'서명 즉시 이전'}).find(c=>c.id==='required-clauses')?.passed,false));
test('copyright condition survives amount correction',()=>{const parsed=structureContract(sentence);const corrected={...parsed,paymentScheduleAmount:parsed.amount};assert.match(corrected.copyrightTransferCondition,/Only after full payment/);assert.equal(validateContract(corrected).filter(c=>c.passed).length,7)});
test('regenerated document is English and matches structured copyright condition',()=>{const parsed=structureContract(sentence);const document=buildContractDocumentText({...parsed,paymentScheduleAmount:parsed.amount});assert.match(document,/Copyright transfer condition: Only after full payment/);assert.doesNotMatch(document,/[가-힣]/) });
test('actual document change blocks approval',()=>assert.equal(signatureGate({checks:validateContract({...valid,amount:1201,paymentScheduleAmount:1201},true),humanApprovalRecorded:true,approvedPdfHash:'old',currentPdfHash:'new'}),false));
test('duplicate eSign is blocked',()=>{const id=createRun();bindFolder(id,'100');assert.throws(()=>bindFolder(id,'101'),/DUPLICATE_ESIGN_BLOCKED/)});
test('arbitrary folder ID cannot be queried',async()=>{process.env.SIGNFENCE_OPERATOR_MODE='true';const response=await statusGet(new Request('http://localhost/api/foxit/status?runId=attacker-folder'));assert.equal(response.status,404);delete process.env.SIGNFENCE_OPERATOR_MODE});
