'use client';
import { useEffect, useMemo, useState } from 'react';
import { ContractData, signatureGate, validateContract } from '../lib/contract';
import { structureContract } from '../lib/structure';
import { buildContractPdfBytes } from '../lib/document';
import { createAgentPlan, FOXIT_MCP_TOOLCHAIN } from '../lib/agent';
import { verifiedFoxitEsignEvidence, verifiedFoxitMcpEvidence } from '../lib/public-evidence';
type AuditEvent={time:string;event:string;detail:string;tone:'info'|'danger'|'success'};
const empty:ContractData={partyA:'',partyB:'',amount:0,paymentScheduleAmount:0,effectiveDate:'',dueDate:'',obligations:[],copyrightTransferCondition:'',requiredClauses:[],extraClauses:[]};
const DEMO_INPUT='온라인 판매자와 외주 디자이너 간 상품 이미지 제작 계약을 작성해 주세요. 계약 본문의 총액은 1,200,000원이고 지급 일정표에는 1,020,000원으로 기재되어 있습니다. 결과물은 상품 이미지 10개, 수정은 최대 2회, 납기일은 2026년 9월 30일입니다. 결과물의 저작권은 계약 대금 전액이 지급된 후 판매자에게 이전됩니다.';
const shortHash=(hash:string|null)=>hash?`${hash.slice(0,12)}…${hash.slice(-8)}`:'Not recorded';
export default function Home(){
 const[prompt,setPrompt]=useState(DEMO_INPUT);const[contract,setContract]=useState<ContractData>(empty);const[currentHash,setCurrentHash]=useState<string|null>(null);const[documentState,setDocumentState]=useState<'idle'|'loading'|'ready'|'error'>('idle');const[approvedHash,setApprovedHash]=useState<string|null>(null);const[approved,setApproved]=useState(false);const[changedAfterApproval,setChangedAfterApproval]=useState(false);const[events,setEvents]=useState<AuditEvent[]>([]);const[structureError,setStructureError]=useState('');const[pdfUrl,setPdfUrl]=useState<string|null>(null);const[pdfBytes,setPdfBytes]=useState<Uint8Array|null>(null);
 useEffect(()=>()=>{if(pdfUrl)URL.revokeObjectURL(pdfUrl)},[pdfUrl]);
 const replacePdf=(bytes:Uint8Array|null)=>{setPdfUrl(previous=>{if(previous)URL.revokeObjectURL(previous);return bytes?URL.createObjectURL(new Blob([bytes],{type:'application/pdf'})):null});setPdfBytes(bytes)};
 const checks=useMemo(()=>validateContract(contract,changedAfterApproval),[contract,changedAfterApproval]);const failed=checks.filter(c=>!c.passed);const canSign=signatureGate({checks,humanApprovalRecorded:approved,approvedPdfHash:approvedHash,currentPdfHash:currentHash});const hasStructured=Boolean(contract.partyA&&contract.partyB);const addEvent=(event:string,detail:string,tone:AuditEvent['tone'])=>setEvents(items=>[...items,{time:new Date().toISOString(),event,detail,tone}]);
 const agentPlan=useMemo(()=>{try{return createAgentPlan(contract,FOXIT_MCP_TOOLCHAIN,checks)}catch{return null}},[contract,checks]);
 const structureInput=()=>{try{const parsed=structureContract(prompt);setContract(parsed);setStructureError('');setCurrentHash(null);replacePdf(null);setApproved(false);setApprovedHash(null);setChangedAfterApproval(false);setDocumentState('idle');addEvent('CONTRACT_STRUCTURED','Deterministic parser · structured contract ready','info');if(parsed.amount!==parsed.paymentScheduleAmount)addEvent('SIGNATURE_BLOCKED','Amount mismatch detected before signing','danger')}catch(error){const message=error instanceof Error?error.message:'STRUCTURE_FAILED';setStructureError(message);addEvent('STRUCTURE_FAILED',`${message} · no fallback used`,'danger')}};
 const generateDocument=async(next=contract)=>{setDocumentState('loading');addEvent('PDF_GENERATION_STARTED','Interactive public demo · local deterministic PDF · no paid API','info');try{const bytes=buildContractPdfBytes(next);const digest=await crypto.subtle.digest('SHA-256',bytes);const hash=Array.from(new Uint8Array(digest)).map(v=>v.toString(16).padStart(2,'0')).join('');replacePdf(bytes);setCurrentHash(hash);setDocumentState('ready');addEvent('PDF_READY',`${bytes.length} bytes · valid %PDF file · SHA-256 ${shortHash(hash)}`,'success');return hash}catch(error){setDocumentState('error');addEvent('PDF_GENERATION_FAILED',error instanceof Error?error.message:'Unknown error','danger');return null}};
 const fixAmount=()=>{const next={...contract,paymentScheduleAmount:contract.amount};setContract(next);setCurrentHash(null);replacePdf(null);setApproved(false);setApprovedHash(null);setChangedAfterApproval(false);setDocumentState('idle');addEvent('AMOUNT_CORRECTED',`Payment schedule changed to KRW ${contract.amount.toLocaleString()}`,'info')};
 const recordApproval=()=>{if(failed.length||!currentHash)return;setApproved(true);setApprovedHash(currentHash);setChangedAfterApproval(false);addEvent('HUMAN_APPROVAL_RECORDED',`SHA-256 ${shortHash(currentHash)}`,'success')};
 const mutateDocument=async()=>{if(!approved)return;const next={...contract,amount:contract.amount+10_000,paymentScheduleAmount:contract.amount+10_000};setContract(next);addEvent('DOCUMENT_EDITED',`Contract amount changed to KRW ${next.amount.toLocaleString()}`,'danger');const hash=await generateDocument(next);if(hash&&hash!==approvedHash){setApproved(false);setChangedAfterApproval(true);addEvent('APPROVAL_REVOKED','Prior approval retained as REVOKED','danger');addEvent('SIGNATURE_BLOCKED','Document hash no longer matches approval','danger')}};
 const revalidateDocument=()=>{if(!changedAfterApproval||!currentHash)return;setChangedAfterApproval(false);addEvent('DOCUMENT_REVALIDATED','Seven deterministic checks rerun on current document','success')};
 return <main className="app-shell"><header className="topbar"><div className="brand"><span className="brand-mark">SF</span><div><strong>SignFence AI</strong><small>Evidence-based signing boundary</small></div></div><div className="mode"><span className="pulse"/>Developer / Test mode</div></header>
 <section className="hero"><div><p className="eyebrow">FOXIT TRACK MVP · SAFE PUBLIC DEMO</p><h1>The agent prepares.<br/><em>The human decides.</em></h1></div><div className={`verdict ${canSign?'ready':hasStructured?'blocked':'waiting'}`}><span>{canSign?'READY FOR OPERATOR ESIGN':hasStructured?'SIGNATURE BLOCKED':'READY FOR CONTRACT INPUT'}</span><strong>{hasStructured?`${checks.filter(c=>c.passed).length}/7 checks passed`:'Paste a contract request to begin'}</strong></div></section>
 <nav className="flow" aria-label="Contract workflow">{['Input','Document','Validate','Block','Correct','Approve','eSign','Complete'].map((step,index)=><div className={index<4||canSign&&index<7?'active':''} key={step}><b>{index+1}</b><span>{step}</span></div>)}</nav>
 <section className="workspace-grid"><article className="panel contract-panel"><div className="panel-head"><div><span className="kicker">SYNTHETIC TEST INPUT · NOT A REAL CONTRACT</span><h2>Natural-language contract</h2></div><span className="api-badge">{documentState==='ready'?'DEMO DOCUMENT READY':'PAID APIS LOCKED'}</span></div>
 <div className="prompt-box"><label>Contract instruction<textarea value={prompt} onChange={e=>setPrompt(e.target.value)} aria-label="Synthetic contract instruction"/><span className="input-translation">English: Create a product-image services agreement between an online seller and a freelance designer. The contract total is KRW 1,200,000, while the payment schedule states KRW 1,020,000. Deliverables are 10 product images, with up to two revisions, due September 30, 2026. Copyright transfers to the seller only after the full contract amount has been paid.</span></label><button onClick={structureInput}>Structure input</button></div>{structureError&&<p className="error-copy">FAILED · {structureError} · no fallback used</p>}<details className="json-details"><summary>View structured contract JSON</summary><pre className="structured-json" aria-label="Structured contract JSON">{JSON.stringify(contract,null,2)}</pre></details>
 <div className="parties"><div><small>PARTY A · ONLINE SELLER</small><strong>{contract.partyA||'Not parsed'}</strong></div><span>↔</span><div><small>PARTY B · FREELANCE DESIGNER</small><strong>{contract.partyB||'Not parsed'}</strong></div></div><div className="amount-grid"><label>Contract total<input value={contract.amount.toLocaleString()} readOnly/><small>KRW</small></label><label className={failed.some(i=>i.id==='amount')?'field-error':''}>Payment schedule<input value={contract.paymentScheduleAmount.toLocaleString()} readOnly/><small>KRW</small></label></div>
 <div className="terms"><div><span>Deliverables</span><b>{contract.obligations.length?'10 product images':'Not parsed'}</b></div><div><span>Revisions</span><b>{contract.obligations.length?'Maximum 2 rounds':'Not parsed'}</b></div><div><span>Due date</span><b>{contract.dueDate?'September 30, 2026':'Not parsed'}</b></div></div><div className="copyright-term"><span>COPYRIGHT TRANSFER</span><b>{contract.copyrightTransferCondition||'Not parsed'}</b></div>
 <div className="actions"><button onClick={()=>generateDocument()} disabled={documentState==='loading'||!contract.partyA}>{documentState==='loading'?'Generating…':'Generate contract PDF'}</button><button className="primary" onClick={fixAmount} disabled={!contract.partyA||documentState!=='ready'||!failed.some(i=>i.id==='amount')}>Correct payment amount</button><button onClick={recordApproval} disabled={failed.length>0||approved||!currentHash}>Human approve & lock hash</button><button onClick={mutateDocument} disabled={!approved||documentState==='loading'}>Change document + regenerate</button><button onClick={revalidateDocument} disabled={!changedAfterApproval||!currentHash}>Revalidate changed document</button></div>
 {pdfUrl&&<section className="pdf-result" aria-label="Generated contract PDF"><div className="pdf-result-head"><div><span className="kicker">REAL USER RESULT</span><h2>Generated contract PDF</h2><small>{pdfBytes?.length.toLocaleString()} bytes · SHA-256 {shortHash(currentHash)}</small></div><a className="download-button" href={pdfUrl} download="signfence-synthetic-contract.pdf">Download PDF</a></div><iframe title="Generated synthetic contract PDF preview" src={pdfUrl}/></section>}</article>
 <aside className="panel checks-panel"><div className="panel-head"><div><span className="kicker">DETERMINISTIC ENGINE</span><h2>7 policy checks</h2></div><span className="score">{checks.filter(c=>c.passed).length}/7</span></div><div className="check-list">{checks.map(check=><div className={check.passed?'pass':'fail'} key={check.id}><span className="check-icon">{check.passed?'✓':'!'}</span><div><strong>{check.label}</strong><small>{check.detail}</small></div></div>)}</div><div className="gate-code"><small>SINGLE SIGNATURE GATE</small><code>allSevenChecksPassed<br/>&amp;&amp; humanApprovalRecorded<br/>&amp;&amp; approvedPdfHash === currentPdfHash</code><span className={canSign?'gate-open':'gate-closed'}>{canSign?'TRUE · OPERATOR MAY SEND':'FALSE · ESIGN DENIED'}</span></div><p className="operator-note"><b>OPERATOR-ONLY LIVE APIs</b><br/>Protected to prevent unauthorized credits and email sends. This public demo performs no Foxit API calls.</p></aside></section>
 <section className="agent-summary"><div><span>EXPLAINABLE DETERMINISTIC AGENT</span><b>No LLM used</b></div><p>Signing permission is never delegated to the agent. eSign is called directly only after deterministic checks and human approval.</p></section>
 <section className="mode-grid four"><div><b>INTERACTIVE PUBLIC DEMO</b><span>Structure · validate · approve · revoke · download PDF</span></div><div><b>VERIFIED LIVE FOXIT MCP RUN</b><span>Actual Foxit MCP tool call · sanitized evidence</span></div><div><b>VERIFIED LIVE FOXIT eSIGN RUN</b><span>Human-signed TEST MODE result · sanitized</span></div><div><b>OPERATOR-ONLY LIVE APIs</b><span>Protected to prevent unauthorized credits and email sends</span></div></section>
 <section className="agent-strip" aria-label="Agent and Foxit tool boundary"><div><small>PLAIN PROMPT</small><b>Korean synthetic contract instruction</b></div><div><small>DETERMINISTIC AGENT PLAN</small><b>{agentPlan?'Structure → MCP PDF → seven checks':'Awaiting valid structured input'}</b></div><div><small>SELECTED FOXIT MCP TOOL</small><b>{agentPlan?.selectedTool??'Not selected'}</b></div><div><small>MCP RESULT</small><b>Actual Foxit MCP tool call · verified evidence below</b></div><div><small>DETERMINISTIC POLICY RESULT</small><b>{failed.length?'BLOCK':agentPlan?.nextAction??'BLOCK'}</b></div><div><small>HUMAN DECISION REQUIRED</small><b>{failed.length?'Resolve failed checks':'Explicit approval required'}</b></div><div><small>FOXIT eSIGN DIRECT API — OUTSIDE MCP</small><b>Operator-only · locked</b></div></section>
 <section className="live-evidence" aria-label="Read-only verified Foxit evidence"><article><header><span>{verifiedFoxitMcpEvidence.label}</span><b>READ-ONLY · SANITIZED</b></header><div className="evidence-grid"><p><small>OFFICIAL SERVER</small><strong>v{verifiedFoxitMcpEvidence.version}</strong></p><p className="wide"><small>ACTUAL TOOLCHAIN</small><code>{verifiedFoxitMcpEvidence.toolchain.join(' → ')}</code></p><p><small>PDF RESULT</small><strong>{verifiedFoxitMcpEvidence.pdfBytes.toLocaleString()} bytes</strong></p><p><small>SHA-256</small><code>{verifiedFoxitMcpEvidence.sha256Short}</code></p><p><small>DETERMINISTIC CHECKS</small><strong>{verifiedFoxitMcpEvidence.checksPassed}/{verifiedFoxitMcpEvidence.checksTotal}</strong></p><p><small>FAILED POLICY</small><strong>{verifiedFoxitMcpEvidence.failedCheck}</strong></p><p><small>AGENT NEXT ACTION</small><strong className="blocked-text">{verifiedFoxitMcpEvidence.nextAction}</strong></p></div><footer>{verifiedFoxitMcpEvidence.dataClassification} · Full task ID, credentials, source PDF, and private checkpoint excluded.</footer></article><article className="esign-proof"><header><span>{verifiedFoxitEsignEvidence.label}</span><b>READ-ONLY · SANITIZED</b></header><div className="evidence-grid"><p><small>STATUS</small><strong>{verifiedFoxitEsignEvidence.status}</strong></p><p><small>ENVIRONMENT</small><strong>{verifiedFoxitEsignEvidence.environment}</strong></p><p><small>FINAL PDF SHA-256</small><code>{verifiedFoxitEsignEvidence.sha256Short}</code></p></div><footer>eSign direct API — outside MCP. Email, Folder ID, security links, activity records, and completed PDF excluded.</footer></article></section>
 <section className="bottom-grid"><article className="panel hash-panel"><div className="panel-head"><div><span className="kicker">DOCUMENT INTEGRITY</span><h2>Approval-bound SHA-256</h2></div><span className="api-badge muted">INTERACTIVE PUBLIC DEMO</span></div><div className="hash-row"><span>Approved document</span><code>{shortHash(approvedHash)}</code></div><div className="hash-row"><span>Current document</span><code>{shortHash(currentHash)}</code></div><div className={`integrity ${approvedHash&&approvedHash===currentHash?'match':''}`}>{approvedHash?approvedHash===currentHash?'HASH MATCH · APPROVAL VALID':'DOCUMENT CHANGED · APPROVAL REVOKED':'AWAITING HUMAN APPROVAL'}</div></article>
 <article className="panel audit-panel"><div className="panel-head"><div><span className="kicker">SESSION EVIDENCE</span><h2>Session audit log</h2></div><span className="api-badge muted">CLIENT SESSION · NOT TAMPER-PROOF</span></div><div className="verified-proof"><span>VERIFIED LIVE FOXIT eSIGN RUN</span><b>REAL PRE-VERIFIED RESULT · EXECUTED</b><code>Final SHA-256 {verifiedFoxitEsignEvidence.sha256Short}</code><small>Direct eSign API outside MCP · TEST MODE · sanitized</small></div><div className="audit-log">{events.slice().reverse().map((item,index)=><div className={item.tone} key={`${item.event}-${index}`}><time>{item.time}</time><strong>{item.event}</strong><span>{item.detail}</span></div>)}</div></article></section></main>;
}
