'use client';
import {useEffect,useMemo,useState} from 'react';
import {ContractData,signatureGate,validateContract} from '../lib/contract';
import {structureContract} from '../lib/structure';
import {buildContractPdfBytes} from '../lib/document';
import {verifiedFoxitEsignEvidence,verifiedFoxitMcpEvidence} from '../lib/public-evidence';
type Stage='input'|'problem'|'review'|'approved'|'revoked'|'ready';
const empty:ContractData={partyA:'',partyB:'',amount:0,paymentScheduleAmount:0,effectiveDate:'',dueDate:'',obligations:[],copyrightTransferCondition:'',requiredClauses:[],extraClauses:[]};
const sample='온라인 판매자와 외주 디자이너 간 상품 이미지 제작 계약을 작성해 주세요. 계약 본문의 총액은 1,200,000원이고 지급 일정표에는 1,020,000원으로 기재되어 있습니다. 결과물은 상품 이미지 10개, 수정은 최대 2회, 납기일은 2026년 9월 30일입니다. 결과물의 저작권은 계약 대금 전액이 지급된 후 판매자에게 이전됩니다.';
const labels=['계약 입력','AI 확인','문제 수정','사람 승인','서명 요청'];
const positions:Record<Stage,number>={input:0,problem:2,review:3,approved:3,revoked:2,ready:4};
const short=(v:string|null)=>v?v.slice(0,10)+'…'+v.slice(-8):'아직 없음';
export default function Home(){
 const[stage,setStage]=useState<Stage>('input'),[prompt,setPrompt]=useState(sample),[contract,setContract]=useState<ContractData>(empty),[hash,setHash]=useState<string|null>(null),[approvedHash,setApprovedHash]=useState<string|null>(null),[approved,setApproved]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[pdfUrl,setPdfUrl]=useState<string|null>(null),[events,setEvents]=useState<string[]>([]);
 useEffect(()=>()=>{if(pdfUrl)URL.revokeObjectURL(pdfUrl)},[pdfUrl]);
 const checks=useMemo(()=>validateContract(contract,stage==='revoked'),[contract,stage]);
 const canSign=signatureGate({checks,humanApprovalRecorded:approved,approvedPdfHash:approvedHash,currentPdfHash:hash});
 const note=(s:string)=>setEvents(x=>[...x,new Date().toLocaleTimeString('ko-KR')+' · '+s]);
 const makePdf=async(next:ContractData)=>{const bytes=buildContractPdfBytes(next);const digest=await crypto.subtle.digest('SHA-256',bytes);const h=Array.from(new Uint8Array(digest)).map(v=>v.toString(16).padStart(2,'0')).join('');setPdfUrl(old=>{if(old)URL.revokeObjectURL(old);return URL.createObjectURL(new Blob([bytes],{type:'application/pdf'}))});setHash(h);return h};
 const start=async()=>{setBusy(true);setError('');try{const parsed=structureContract(prompt);setContract(parsed);setApproved(false);setApprovedHash(null);await makePdf(parsed);note('계약 내용을 확인하고 PDF를 만들었습니다.');setStage(parsed.amount===parsed.paymentScheduleAmount?'review':'problem')}catch{setError('계약 금액과 날짜를 포함해 다시 작성해 주세요.')}finally{setBusy(false)}};
 const fix=async()=>{setBusy(true);const next={...contract,paymentScheduleAmount:contract.amount};setContract(next);await makePdf(next);note('서로 달랐던 금액을 계약 총액에 맞췄습니다.');setStage('review');setBusy(false)};
 const approve=()=>{if(!hash)return;setApproved(true);setApprovedHash(hash);setStage('approved');note('사람이 현재 계약서를 승인했습니다.')};
 const change=async()=>{setBusy(true);const next={...contract,amount:contract.amount+10000,paymentScheduleAmount:contract.amount+10000};setContract(next);await makePdf(next);setApproved(false);setStage('revoked');note('승인 뒤 계약이 바뀌어 승인을 자동 취소했습니다.');setBusy(false)};
 const reset=()=>{setStage('input');setContract(empty);setHash(null);setApprovedHash(null);setApproved(false);setPdfUrl(null);setEvents([]);setError('')};
 const step=positions[stage];
 return <main className="consumer-shell"><header><div className="brand"><span>SF</span><strong>SignFence AI</strong></div><button className="quiet" onClick={reset}>처음부터</button></header>
 <nav className="stepper" aria-label="진행 단계">{labels.map((x,i)=><div className={i<step?'done':i===step?'current':''} key={x}><b>{i<step?'✓':i+1}</b><span>{x}</span></div>)}</nav>
 <section className={'task '+stage} aria-live="polite">
 {stage==='input'&&<><p className="kicker">1단계 · 계약 입력</p><h1>어떤 계약서가 필요한가요?</h1><p className="lead">평소 말하듯 입력하세요. 한국어와 영어를 모두 이해합니다.</p><label className="input"><span>계약 내용</span><textarea value={prompt} onChange={e=>setPrompt(e.target.value)}/></label>{error&&<p className="friendly-error">{error}</p>}<button className="primary" onClick={start} disabled={busy||prompt.length<20}>{busy?'계약서를 만들고 있어요…':'AI로 계약 확인하기'}</button></>}
 {stage==='problem'&&<><div className="icon warning">!</div><p className="kicker">AI 확인 결과</p><h1>금액이 서로 다릅니다</h1><p className="lead">계약 총액과 지급 예정 금액이 달라 잘못 서명할 수 있습니다.</p><div className="compare"><div><span>계약 총액</span><b>{contract.amount.toLocaleString()}원</b></div><div><span>지급 예정</span><b>{contract.paymentScheduleAmount.toLocaleString()}원</b></div></div><p className="notice">잘못된 금액으로 서명하지 않도록 지금은 서명을 막아 두었습니다.</p><button className="primary" onClick={fix} disabled={busy}>{busy?'수정하고 있어요…':'계약 총액에 맞게 수정하기'}</button></>}
 {stage==='review'&&<><div className="icon success">✓</div><p className="kicker">확인 완료</p><h1>계약서를 확인해 주세요</h1><p className="lead">금액과 필수 내용이 모두 맞습니다. 읽은 뒤 직접 승인해 주세요.</p><div className="summary"><div><span>계약 당사자</span><b>{contract.partyA} ↔ {contract.partyB}</b></div><div><span>계약 금액</span><b>{contract.amount.toLocaleString()}원</b></div><div><span>납기일</span><b>{contract.dueDate}</b></div></div>{pdfUrl&&<div className="pdf"><iframe title="계약서 미리보기" src={pdfUrl}/><a href={pdfUrl} download="signfence-contract.pdf">PDF 내려받기</a></div>}<button className="primary" onClick={approve}>이 계약서 승인하기</button></>}
 {stage==='approved'&&<><div className="icon success">✓</div><p className="kicker">사람 승인 완료</p><h1>이 계약서만 승인했습니다</h1><p className="lead">이후 글자나 금액이 하나라도 바뀌면 승인은 자동으로 취소됩니다.</p><div className="approval"><span>승인된 계약 금액</span><b>{contract.amount.toLocaleString()}원</b><small>현재 PDF와 승인본이 일치합니다</small></div><button className="primary" onClick={change} disabled={busy}>{busy?'변경을 확인하고 있어요…':'승인 후 변경 보호 체험하기'}</button><button className="quiet next" onClick={()=>setStage('ready')}>변경 체험 없이 서명 단계로 이동</button></>}
 {stage==='revoked'&&<><div className="icon danger">×</div><p className="kicker danger-text">서명 중단</p><h1>계약서가 변경되어<br/>서명을 중단했습니다</h1><p className="lead">승인할 때보다 계약 금액이 바뀌었습니다. 이전 승인은 더 이상 사용할 수 없습니다.</p><div className="compare revoked"><div><span>승인했던 금액</span><b>{(contract.amount-10000).toLocaleString()}원</b></div><div><span>현재 금액</span><b>{contract.amount.toLocaleString()}원</b></div></div><button className="primary" onClick={()=>{setStage('review');note('변경된 계약서를 다시 확인했습니다.')}}>변경된 계약서 다시 확인하기</button></>}
 {stage==='ready'&&<><div className="icon success">✓</div><p className="kicker">서명 요청 준비 완료</p><h1>Foxit으로 서명할 준비가 됐습니다</h1><p className="lead">공개 체험에서는 비용과 이메일 오발송을 막기 위해 새 요청을 보내지 않습니다. 기존 TEST MODE 실증 결과를 보여드립니다.</p><div className="foxit"><div><span>Foxit MCP</span><b>계약 PDF 생성 완료</b></div><div><span>사람 서명</span><b>TEST MODE · EXECUTED</b></div><div><span>승인 상태</span><b>{canSign?'승인본과 일치':'안전하게 잠김'}</b></div></div>{pdfUrl&&<a className="primary link" href={pdfUrl} download="signfence-final-contract.pdf">최종 계약서 PDF 받기</a>}</>}
 </section>
 <details className="technical"><summary>기술 세부정보</summary><div className="tech-grid"><section><h2>7가지 안전 확인</h2>{checks.map(c=><p key={c.id}><b>{c.passed?'통과':'확인 필요'}</b> · {c.label}</p>)}</section><section><h2>문서 무결성</h2><p>현재 PDF: <code>{short(hash)}</code></p><p>승인 PDF: <code>{short(approvedHash)}</code></p></section><section><h2>Foxit MCP 실증</h2><p>{verifiedFoxitMcpEvidence.toolchain.join(' → ')}</p><p>{verifiedFoxitMcpEvidence.pdfBytes.toLocaleString()} bytes · {verifiedFoxitMcpEvidence.sha256Short}</p></section><section><h2>Foxit eSign 실증</h2><p>{verifiedFoxitEsignEvidence.environment} · {verifiedFoxitEsignEvidence.status}</p><p>{verifiedFoxitEsignEvidence.sha256Short}</p></section><section className="wide"><h2>구조화 데이터</h2><pre>{JSON.stringify(contract,null,2)}</pre></section><section className="wide"><h2>이 세션의 기록</h2>{events.map((e,i)=><p key={i}>{e}</p>)}</section></div></details>
 <footer>체험용 데이터입니다 · 공개 화면에서는 Foxit 크레딧 사용과 이메일 발송이 잠겨 있습니다.</footer></main>
}
